### ISSUE TITLE
Undefined semantic on comparison between a `Tensor` and its permutations

### ISSUE THREAD

**Issue by jofrevalles** [bsc-quantic/Tensors.jl#27]
I have noticed a potential area for improvement regarding the use of `isequal` and `isapprox` functions for our `Tensor` struct. Currently, these functions distinguish a tensor from a permuted version of the same tensor as different.

From a mathematical perspective, one might argue that a tensor and its permutation should be treated as essentially the same entity. This is because the labels of the tensor already indicate that the data is permuted. Nevertheless, the current implementation of `isequal` and `isapprox` treats them as distinct. Here's a simple illustration:
```julia
julia> using Tensors

julia> A = Tensor(rand(2, 2, 2), (:i, :j, :k))
2×2×2 Tensor{Float64, 3, Array{Float64, 3}}: ...

julia> B = permutedims(A, (2, 1, 3))
2×2×2 Tensor{Float64, 3, Array{Float64, 3}}: ...

julia> A ≈ B
false

julia> A == B
false
```

My suggestion is to consider adjusting the `isequal` and `isapprox` functions to return true in cases like this. I believe this adjustment will not only make the comparison of different tensors more flexible but will also enhance the user-friendliness of our library.

**Comment by mofeing** [comment]
I agree with you. We should bet on mathematical coherence.

A question that I have is how would we implement the comparisons: should we permute one of the arrays to make the comparison or should we create some kind of specialization of `eachindex` to iterate both tensors in the same way?

**Comment by mofeing** [comment]
Also, if a user wants to use legacy/Julia-like comparison, it can be done by calling `parent` on the tensors.
